#!/usr/bin/env ruby
require 'config.rb'
require 'fileutils'

if not ARGV[0]
  raise "Provide an argument"
end

files = ["#{ARGV[0]}.p12", "ta.key"]

files.each do |file|
  if not File.exists?("#{CA_DIR}/#{file}")
    raise "File #{file} does not exist"
  end
end

dir = "#{ARGV[0]}.tblk"

if File.directory?(dir)
  raise "Directory #{dir} exists"
end

FileUtils.mkdir_p("#{dir}/")

files.each do |file|
  FileUtils.copy("#{CA_DIR}/#{file}", "#{dir}/#{file}")
end

config = %{
port 1194
mssfix 1300
client
tls-client
pkcs12 #{ARGV[0]}.p12
comp-lzo no
keepalive 10 60
ping-timer-rem
push-peer-info
persist-tun
persist-key
verb 3
proto udp
pull
tls-auth ta.key 0
nobind
remote #{HOST} 1194
resolv-retry infinite
}

File.open("#{dir}/Contents/Resources/config.ovpn", 'w') do |f|
  f.write(config)
end

`zip -r #{dir}.zip ./#{dir}`
FileUtils.rm_rf dir
